dist: focal
language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10.4'
  - '3.11'
  - '3.12-dev'
  - 'pypy2'
  - 'pypy3'

before_install:
  - sudo apt-get -y install libzbar0

install:
  - pip install -r requirements-testing.txt
  - |
    if [[ ! $TRAVIS_PYTHON_VERSION =~ ^2 && ! $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then
      pip install flake8;
      pip install "mypy<0.950";
    fi

script:
  - |
    if [[ ! $TRAVIS_PYTHON_VERSION =~ ^2 && ! $TRAVIS_PYTHON_VERSION =~ ^pypy ]]; then
      flake8 segno;
      flake8 tests/;
      mypy segno;
    fi
  - pytest
